apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: 34.5.0
    helm:
      values: |
        service:
          type: LoadBalancer
        ports:
          web:
            redirections:
              entryPoint:
                to: websecure
                scheme: https
        providers:
          kubernetesCRD:
            enabled: true
            allowCrossNamespace: true
            allowExternalNameServices: true
          kubernetesIngress:
            enabled: true
            allowExternalNameServices: true
        ingressRoute:
          dashboard:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
