---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCS3p5EV/xsrHGoCDA/SqwElDfcPsqOMQiFQt1899lg/EYYwf+ZOAu2CLkfYar5sIDdClj5ubc20bfeNGn8R8jH/8rS8NcL0IPgUi7VCUc28pP9+bo07DFTNNjpJf0NB/kfe+7Haxl1adrqsQcPGghPOW85JwkzxrdlXov7DBELz84zbjWx+pkQD9yvREBRacBuXseg+ZgE6QiI7m9+Py8xCIJWbRuG16zjdBsd8gAjahHEQyCHzeLpiQfMP7R4LSJQJDSy41Qury5OIloMS4x7LOzgZAN9GRbtEq51TYLW6W4+s+g2wmjY+y55y+lCPGmaEDYuiEdDNa2Ql9fPcD07ctovRBxP7/C2hd4/bVgpmvy2l+jz/zMS7D9nqdK50AjzOqy000RIKdCE2Bd90ueR8zBplj+0MKBuD4pnDUjVJU1GGVgJxk+SgSFKLzI9jtibgwyVU7fO7OTNvocMql+Gm7+9GACal+rROPVmtVwZVUAgOPIyD7Hgt7gTtH6jqoyZErP27y2TIOUlzGHogMPg37r/jz3i/RbwyuZLCg76Nx0n8VT0p6jvwizfY3qr618AOQqSbk5i2pzApfX6rt2xaDPBcKJDyIgNKvEtzYRsvAmGxlWOxjsAL7fic4r/jEIHF421nzk7o07aLnJZ8jnfL61Duwrjz91Ct1pTVa+/E81+2reuGq7UIni6x3TDQ3DfdJQyoNE9NqfT4UnvDzgyEFuXUEg8La6DWmT5p2Mctw==
    admin-user: AgCftTc0PobNcKWb+3LWh0hodBN9YKxoZQSQNyvA0FxzlwwK553oCt46Aawh1muLGivfvrXpB2ORUgEYJkxAaaA/mllOCvGMih3Twj+msp3tFa8NNrgb1Fgsfs91FDT/18tVh9ZucLy+MDSNcFknd4jOhCQZbQKgBzBE96nkCgKAlmSbuGmCV9uz5iskedMfTj/t9jQxxUa4WdmuzWQHIMnf5qVbs444bh+1jN+TZysA52ZeEEYExg5dy+YjGwK7giosfh7ypD5GhnMOdMo0vOVH1WO/X9FERzK9/aVtRu2rWgJU38PLM9A2i/vDupdAsIXZeGPMylZGY7Zg5yqNu9WwD6+TkGMzKZKR9K6WyM7AglUE+pqKeVniGNc3JS9r+72zlDPJ+NGnWOhPlumhifP9CEQvE/MHDyFnFcZiJY/OYZce/p2AoQ5AOkTN1CQ/NrKTlt8L6l6JBTkDJ8Dfz+4Vuy4wZ/N12l/wyVx72afGunuVh6/YxaVVpNBl8oCH3zW9M3A0yfWgsJfRmtzoE67fnHflY7aKxoBleXBr9lUAtuBcFLixGmKifH2AYiN29xFSwegqYKFzD3ap6H8XxNrPidQOppXQBc2mGmhRiPTm9oo8cnyj3nsdxLhkqVSgKGLWZwKOGZSg6iwkPxVG9iFI8HyHcKK2zv38syPf716doT3Yrzb7JuMy42TNIDrVBOiBSKDTMA==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
